var annotated_dup =
[
    [ "ankerl", null, [
      [ "nanobench", null, [
        [ "detail", null, [
          [ "PerfCountSet", "structankerl_1_1nanobench_1_1detail_1_1PerfCountSet.html", null ]
        ] ],
        [ "Bench", "classankerl_1_1nanobench_1_1Bench.html", "classankerl_1_1nanobench_1_1Bench" ],
        [ "BigO", "classankerl_1_1nanobench_1_1BigO.html", null ],
        [ "Config", "structankerl_1_1nanobench_1_1Config.html", null ],
        [ "Result", "classankerl_1_1nanobench_1_1Result.html", null ],
        [ "Rng", "classankerl_1_1nanobench_1_1Rng.html", "classankerl_1_1nanobench_1_1Rng" ]
      ] ]
    ] ],
    [ "internal", null, [
      [ "BigInteger", "classinternal_1_1BigInteger.html", null ],
      [ "DecodedStream", "classinternal_1_1DecodedStream.html", null ],
      [ "DiyFp", "structinternal_1_1DiyFp.html", "structinternal_1_1DiyFp" ],
      [ "Double", "classinternal_1_1Double.html", null ],
      [ "GenericRegex", "classinternal_1_1GenericRegex.html", null ],
      [ "GenericRegexSearch", "classinternal_1_1GenericRegexSearch.html", null ],
      [ "Hasher", "classinternal_1_1Hasher.html", null ],
      [ "ISchemaStateFactory", "classinternal_1_1ISchemaStateFactory.html", null ],
      [ "ISchemaValidator", "classinternal_1_1ISchemaValidator.html", null ],
      [ "IsRefCounted", "structinternal_1_1IsRefCounted.html", null ],
      [ "IsRefCounted< T, typename internal::EnableIfCond< T::kRefCounted >::Type >", "structinternal_1_1IsRefCounted_3_01T_00_01typename_01internal_1_1EnableIfCond_3_01T_1_1kRefCounted_01_4_1_1Type_01_4.html", null ],
      [ "IValidationErrorHandler", "classinternal_1_1IValidationErrorHandler.html", null ],
      [ "Schema", "classinternal_1_1Schema.html", null ],
      [ "SchemaValidationContext", "structinternal_1_1SchemaValidationContext.html", null ],
      [ "Stack", "classinternal_1_1Stack.html", null ],
      [ "StreamLocalCopy", "classinternal_1_1StreamLocalCopy.html", null ],
      [ "StreamLocalCopy< Stream, 0 >", "classinternal_1_1StreamLocalCopy_3_01Stream_00_010_01_4.html", null ],
      [ "StreamLocalCopy< Stream, 1 >", "classinternal_1_1StreamLocalCopy_3_01Stream_00_011_01_4.html", null ],
      [ "TokenHelper", "structinternal_1_1TokenHelper.html", null ],
      [ "TokenHelper< Stack, char >", "structinternal_1_1TokenHelper_3_01Stack_00_01char_01_4.html", null ]
    ] ],
    [ "Allocator", "classrapidjson_1_1Allocator.html", null ],
    [ "ASCII", "structASCII.html", null ],
    [ "AutoUTF", "structAutoUTF.html", null ],
    [ "AutoUTFInputStream", "classAutoUTFInputStream.html", "classAutoUTFInputStream" ],
    [ "AutoUTFOutputStream", "classAutoUTFOutputStream.html", "classAutoUTFOutputStream" ],
    [ "BaseReaderHandler", "structBaseReaderHandler.html", "structBaseReaderHandler" ],
    [ "BasicIStreamWrapper", "classBasicIStreamWrapper.html", "classBasicIStreamWrapper" ],
    [ "BasicOStreamWrapper", "classBasicOStreamWrapper.html", null ],
    [ "BenchmarkJson", "classBenchmarkJson.html", null ],
    [ "BenchmarkRepository", "classBenchmarkRepository.html", null ],
    [ "BenchmarkSorting", "classBenchmarkSorting.html", null ],
    [ "CrtAllocator", "classCrtAllocator.html", null ],
    [ "CursorStreamWrapper", "classCursorStreamWrapper.html", "classCursorStreamWrapper" ],
    [ "EncodedInputStream", "classEncodedInputStream.html", null ],
    [ "EncodedInputStream< UTF8<>, MemoryStream >", "classEncodedInputStream_3_01UTF8_3_4_00_01MemoryStream_01_4.html", null ],
    [ "EncodedOutputStream", "classEncodedOutputStream.html", null ],
    [ "Encoding", "classrapidjson_1_1Encoding.html", null ],
    [ "ExportService", "classExportService.html", null ],
    [ "Field", "structField.html", "structField" ],
    [ "FileReadStream", "classFileReadStream.html", "classFileReadStream" ],
    [ "FileWriteStream", "classFileWriteStream.html", "classFileWriteStream" ],
    [ "GenericArray", "classGenericArray.html", null ],
    [ "GenericDocument", "classGenericDocument.html", "classGenericDocument" ],
    [ "GenericInsituStringStream", "structGenericInsituStringStream.html", null ],
    [ "GenericMember", "classGenericMember.html", "classGenericMember" ],
    [ "GenericMemberIterator", "classGenericMemberIterator.html", "classGenericMemberIterator" ],
    [ "GenericMemoryBuffer", "structGenericMemoryBuffer.html", null ],
    [ "GenericObject", "classGenericObject.html", null ],
    [ "GenericPointer", "classGenericPointer.html", "classGenericPointer" ],
    [ "GenericReader", "classGenericReader.html", "classGenericReader" ],
    [ "GenericSchemaDocument", "classGenericSchemaDocument.html", "classGenericSchemaDocument" ],
    [ "GenericSchemaValidator", "classGenericSchemaValidator.html", "classGenericSchemaValidator" ],
    [ "GenericStreamWrapper", "classGenericStreamWrapper.html", null ],
    [ "GenericStringBuffer", "classGenericStringBuffer.html", "classGenericStringBuffer" ],
    [ "GenericStringRef", "structGenericStringRef.html", "structGenericStringRef" ],
    [ "GenericStringStream", "structGenericStringStream.html", "structGenericStringStream" ],
    [ "GenericUri", "classGenericUri.html", "classGenericUri" ],
    [ "GenericValue", "classGenericValue.html", "classGenericValue" ],
    [ "Handler", "classrapidjson_1_1Handler.html", null ],
    [ "IGenericRemoteSchemaDocumentProvider", "classIGenericRemoteSchemaDocumentProvider.html", null ],
    [ "imaxdiv_t", "structimaxdiv__t.html", null ],
    [ "IStorageStrategy", "classIStorageStrategy.html", "classIStorageStrategy" ],
    [ "JsonStorageStrategy", "classJsonStorageStrategy.html", "classJsonStorageStrategy" ],
    [ "Logger", "classLogger.html", null ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "MemoryPoolAllocator", "classMemoryPoolAllocator.html", "classMemoryPoolAllocator" ],
    [ "MemoryStream", "structMemoryStream.html", "structMemoryStream" ],
    [ "Note", "classNote.html", "classNote" ],
    [ "NoteEditor", "classNoteEditor.html", "classNoteEditor" ],
    [ "NoteRepository", "classNoteRepository.html", "classNoteRepository" ],
    [ "NoteWidget", "classNoteWidget.html", "classNoteWidget" ],
    [ "ParseResult", "structParseResult.html", "structParseResult" ],
    [ "PrettyWriter", "classPrettyWriter.html", "classPrettyWriter" ],
    [ "QCPAbstractItem", "classQCPAbstractItem.html", "classQCPAbstractItem" ],
    [ "QCPAbstractLegendItem", "classQCPAbstractLegendItem.html", "classQCPAbstractLegendItem" ],
    [ "QCPAbstractPaintBuffer", "classQCPAbstractPaintBuffer.html", "classQCPAbstractPaintBuffer" ],
    [ "QCPAbstractPlottable", "classQCPAbstractPlottable.html", "classQCPAbstractPlottable" ],
    [ "QCPAbstractPlottable1D", "classQCPAbstractPlottable1D.html", "classQCPAbstractPlottable1D" ],
    [ "QCPAxis", "classQCPAxis.html", "classQCPAxis" ],
    [ "QCPAxisPainterPrivate", "classQCPAxisPainterPrivate.html", "classQCPAxisPainterPrivate" ],
    [ "QCPAxisRect", "classQCPAxisRect.html", "classQCPAxisRect" ],
    [ "QCPAxisTicker", "classQCPAxisTicker.html", "classQCPAxisTicker" ],
    [ "QCPAxisTickerDateTime", "classQCPAxisTickerDateTime.html", "classQCPAxisTickerDateTime" ],
    [ "QCPAxisTickerFixed", "classQCPAxisTickerFixed.html", "classQCPAxisTickerFixed" ],
    [ "QCPAxisTickerLog", "classQCPAxisTickerLog.html", "classQCPAxisTickerLog" ],
    [ "QCPAxisTickerPi", "classQCPAxisTickerPi.html", "classQCPAxisTickerPi" ],
    [ "QCPAxisTickerText", "classQCPAxisTickerText.html", "classQCPAxisTickerText" ],
    [ "QCPAxisTickerTime", "classQCPAxisTickerTime.html", "classQCPAxisTickerTime" ],
    [ "QCPBars", "classQCPBars.html", "classQCPBars" ],
    [ "QCPBarsData", "classQCPBarsData.html", "classQCPBarsData" ],
    [ "QCPBarsGroup", "classQCPBarsGroup.html", "classQCPBarsGroup" ],
    [ "QCPColorGradient", "classQCPColorGradient.html", "classQCPColorGradient" ],
    [ "QCPColorMap", "classQCPColorMap.html", "classQCPColorMap" ],
    [ "QCPColorMapData", "classQCPColorMapData.html", "classQCPColorMapData" ],
    [ "QCPColorScale", "classQCPColorScale.html", "classQCPColorScale" ],
    [ "QCPColorScaleAxisRectPrivate", "classQCPColorScaleAxisRectPrivate.html", "classQCPColorScaleAxisRectPrivate" ],
    [ "QCPCurve", "classQCPCurve.html", "classQCPCurve" ],
    [ "QCPCurveData", "classQCPCurveData.html", "classQCPCurveData" ],
    [ "QCPDataContainer", "classQCPDataContainer.html", "classQCPDataContainer" ],
    [ "QCPDataRange", "classQCPDataRange.html", "classQCPDataRange" ],
    [ "QCPDataSelection", "classQCPDataSelection.html", "classQCPDataSelection" ],
    [ "QCPErrorBars", "classQCPErrorBars.html", "classQCPErrorBars" ],
    [ "QCPErrorBarsData", "classQCPErrorBarsData.html", "classQCPErrorBarsData" ],
    [ "QCPFinancial", "classQCPFinancial.html", "classQCPFinancial" ],
    [ "QCPFinancialData", "classQCPFinancialData.html", "classQCPFinancialData" ],
    [ "QCPGraph", "classQCPGraph.html", "classQCPGraph" ],
    [ "QCPGraphData", "classQCPGraphData.html", "classQCPGraphData" ],
    [ "QCPGrid", "classQCPGrid.html", "classQCPGrid" ],
    [ "QCPItemAnchor", "classQCPItemAnchor.html", "classQCPItemAnchor" ],
    [ "QCPItemBracket", "classQCPItemBracket.html", "classQCPItemBracket" ],
    [ "QCPItemCurve", "classQCPItemCurve.html", "classQCPItemCurve" ],
    [ "QCPItemEllipse", "classQCPItemEllipse.html", "classQCPItemEllipse" ],
    [ "QCPItemLine", "classQCPItemLine.html", "classQCPItemLine" ],
    [ "QCPItemPixmap", "classQCPItemPixmap.html", "classQCPItemPixmap" ],
    [ "QCPItemPosition", "classQCPItemPosition.html", "classQCPItemPosition" ],
    [ "QCPItemRect", "classQCPItemRect.html", "classQCPItemRect" ],
    [ "QCPItemStraightLine", "classQCPItemStraightLine.html", "classQCPItemStraightLine" ],
    [ "QCPItemText", "classQCPItemText.html", "classQCPItemText" ],
    [ "QCPItemTracer", "classQCPItemTracer.html", "classQCPItemTracer" ],
    [ "QCPLabelPainterPrivate", "classQCPLabelPainterPrivate.html", "classQCPLabelPainterPrivate" ],
    [ "QCPLayer", "classQCPLayer.html", "classQCPLayer" ],
    [ "QCPLayerable", "classQCPLayerable.html", "classQCPLayerable" ],
    [ "QCPLayout", "classQCPLayout.html", "classQCPLayout" ],
    [ "QCPLayoutElement", "classQCPLayoutElement.html", "classQCPLayoutElement" ],
    [ "QCPLayoutGrid", "classQCPLayoutGrid.html", "classQCPLayoutGrid" ],
    [ "QCPLayoutInset", "classQCPLayoutInset.html", "classQCPLayoutInset" ],
    [ "QCPLegend", "classQCPLegend.html", "classQCPLegend" ],
    [ "QCPLineEnding", "classQCPLineEnding.html", "classQCPLineEnding" ],
    [ "QCPMarginGroup", "classQCPMarginGroup.html", "classQCPMarginGroup" ],
    [ "QCPPaintBufferPixmap", "classQCPPaintBufferPixmap.html", "classQCPPaintBufferPixmap" ],
    [ "QCPPainter", "classQCPPainter.html", "classQCPPainter" ],
    [ "QCPPlottableInterface1D", "classQCPPlottableInterface1D.html", "classQCPPlottableInterface1D" ],
    [ "QCPPlottableLegendItem", "classQCPPlottableLegendItem.html", "classQCPPlottableLegendItem" ],
    [ "QCPPolarAxisAngular", "classQCPPolarAxisAngular.html", "classQCPPolarAxisAngular" ],
    [ "QCPPolarAxisRadial", "classQCPPolarAxisRadial.html", "classQCPPolarAxisRadial" ],
    [ "QCPPolarGraph", "classQCPPolarGraph.html", "classQCPPolarGraph" ],
    [ "QCPPolarGrid", "classQCPPolarGrid.html", "classQCPPolarGrid" ],
    [ "QCPPolarLegendItem", "classQCPPolarLegendItem.html", "classQCPPolarLegendItem" ],
    [ "QCPRange", "classQCPRange.html", "classQCPRange" ],
    [ "QCPScatterStyle", "classQCPScatterStyle.html", "classQCPScatterStyle" ],
    [ "QCPSelectionDecorator", "classQCPSelectionDecorator.html", "classQCPSelectionDecorator" ],
    [ "QCPSelectionDecoratorBracket", "classQCPSelectionDecoratorBracket.html", "classQCPSelectionDecoratorBracket" ],
    [ "QCPSelectionRect", "classQCPSelectionRect.html", "classQCPSelectionRect" ],
    [ "QCPStatisticalBox", "classQCPStatisticalBox.html", "classQCPStatisticalBox" ],
    [ "QCPStatisticalBoxData", "classQCPStatisticalBoxData.html", "classQCPStatisticalBoxData" ],
    [ "QCPTextElement", "classQCPTextElement.html", "classQCPTextElement" ],
    [ "QCPVector2D", "classQCPVector2D.html", "classQCPVector2D" ],
    [ "QCustomPlot", "classQCustomPlot.html", "classQCustomPlot" ],
    [ "RapidJsonStorageStrategy", "classRapidJsonStorageStrategy.html", "classRapidJsonStorageStrategy" ],
    [ "Schema", "classSchema.html", "classSchema" ],
    [ "SchemaEditor", "classSchemaEditor.html", "classSchemaEditor" ],
    [ "SchemaManager", "classSchemaManager.html", "classSchemaManager" ],
    [ "SchemaValidatingReader", "classSchemaValidatingReader.html", "classSchemaValidatingReader" ],
    [ "SettingsDialog", "classSettingsDialog.html", "classSettingsDialog" ],
    [ "Specification", "structSpecification.html", null ],
    [ "StatisticsDialog", "classStatisticsDialog.html", "classStatisticsDialog" ],
    [ "StatisticsService", "classStatisticsService.html", null ],
    [ "StdAllocator", "classStdAllocator.html", "classStdAllocator" ],
    [ "StdAllocator< void, BaseAllocator >", "classStdAllocator_3_01void_00_01BaseAllocator_01_4.html", "classStdAllocator_3_01void_00_01BaseAllocator_01_4" ],
    [ "Stream", "classrapidjson_1_1Stream.html", null ],
    [ "StreamTraits", "structStreamTraits.html", null ],
    [ "StreamTraits< GenericInsituStringStream< Encoding > >", "structStreamTraits_3_01GenericInsituStringStream_3_01Encoding_01_4_01_4.html", null ],
    [ "StreamTraits< GenericStringStream< Encoding > >", "structStreamTraits_3_01GenericStringStream_3_01Encoding_01_4_01_4.html", null ],
    [ "TagEditor", "classTagEditor.html", "classTagEditor" ],
    [ "TestIO", "classTestIO.html", null ],
    [ "TestModels", "classTestModels.html", null ],
    [ "TestRepository", "classTestRepository.html", null ],
    [ "Transcoder", "structTranscoder.html", null ],
    [ "Transcoder< Encoding, Encoding >", "structTranscoder_3_01Encoding_00_01Encoding_01_4.html", null ],
    [ "UTF16", "structUTF16.html", null ],
    [ "UTF16BE", "structUTF16BE.html", null ],
    [ "UTF16LE", "structUTF16LE.html", null ],
    [ "UTF32", "structUTF32.html", null ],
    [ "UTF32BE", "structUTF32BE.html", null ],
    [ "UTF32LE", "structUTF32LE.html", null ],
    [ "UTF8", "structUTF8.html", null ],
    [ "Writer", "classWriter.html", "classWriter" ]
];