var dir_27d5732336fb04de189cf8ef7e734598 =
[
    [ "error", "dir_2cfb7cd98c40a4cc7ecd0ae1b0eb25a4.html", "dir_2cfb7cd98c40a4cc7ecd0ae1b0eb25a4" ],
    [ "internal", "dir_1a446b91bfdee06756df45bde48460e0.html", "dir_1a446b91bfdee06756df45bde48460e0" ],
    [ "msinttypes", "dir_4ad9343ef8473d3752715648aa4cf317.html", "dir_4ad9343ef8473d3752715648aa4cf317" ],
    [ "allocators.h", "allocators_8h_source.html", null ],
    [ "cursorstreamwrapper.h", "cursorstreamwrapper_8h_source.html", null ],
    [ "document.h", "document_8h.html", "document_8h" ],
    [ "encodedstream.h", "encodedstream_8h_source.html", null ],
    [ "encodings.h", "encodings_8h_source.html", null ],
    [ "filereadstream.h", "filereadstream_8h_source.html", null ],
    [ "filewritestream.h", "filewritestream_8h_source.html", null ],
    [ "fwd.h", "fwd_8h_source.html", null ],
    [ "istreamwrapper.h", "istreamwrapper_8h_source.html", null ],
    [ "memorybuffer.h", "memorybuffer_8h_source.html", null ],
    [ "memorystream.h", "memorystream_8h_source.html", null ],
    [ "ostreamwrapper.h", "ostreamwrapper_8h_source.html", null ],
    [ "pointer.h", "pointer_8h_source.html", null ],
    [ "prettywriter.h", "prettywriter_8h_source.html", null ],
    [ "rapidjson.h", "rapidjson_8h.html", "rapidjson_8h" ],
    [ "reader.h", "reader_8h.html", "reader_8h" ],
    [ "schema.h", "libs_2rapidjson_2schema_8h_source.html", null ],
    [ "stream.h", "stream_8h_source.html", null ],
    [ "stringbuffer.h", "stringbuffer_8h_source.html", null ],
    [ "uri.h", "uri_8h_source.html", null ],
    [ "writer.h", "writer_8h_source.html", null ]
];