@startuml
title Стан "Потоку" програміста
robust "Рівень продуктивності" as P

@0
P is "Прокрастинація (дивлюсь меми)"
@20
P is "Розминка (читаю умову лаби)"
@40
P is "Входження в Потік (пишу лабу)"
@60
P is "МАКСИМАЛЬНА ПРОДУКТИВНІСТЬ (Flow)"
@75
P is "Переривання (хтось написав у Telegram)"
@80
P is "Намагання згадати, що я робила"
@90
P is "Втома (піду пити чай)"
@100
@enduml