@startuml
title Алгоритм прийняття рішення о 07:00
start
:Пролунав будильник;
if (Скільки годин спав?) then (< 4 години)
  :Спробувати відкрити очі;
  if (Вийшло?) then (ні)
    :Автоматичне переведення на 15 хв;
    detach
  else (так)
    :Згадати, чи сьогодні дедлайн;
  endif
else (> 4 години)
  :Це диво, треба йти;
endif

if (Дедлайн сьогодні?) then (так)
  :Встати через силу;
  :Пити каву (extra strong);
else (ні)
  :Подумати "Там відмічають?";
  if (Відмічають?) then (ні)
    :Спати далі;
    stop
  else (так)
    :Встати і страждати;
  endif
endif
:Вийти з дому;
stop
@enduml