@startuml
title Алгоритм здачі лаби
start
:Прийти на пару;
if (Викладач у доброму гуморі?) then (так)
  :Показати код;
  if (Працює?) then (ні)
    :Сказати "Це магія, вдома працювало";
    stop
  else (так)
    :Відповідати на питання;
    while (Викладач запитує "А чому тут цей патерн?") is (студент мовчить)
      :Згадати все, що чув на лекції;
    endwhile
    :Отримати бали;
  endif
else (ні)
  :Сховатися за монітором;
  :Чекати наступну пару;
endif
stop
@enduml