@startuml
title Алгоритм перевірки та оцінювання

start
:Викладач відкриває список робіт;
:Вибір конкретної роботи;
if (Робота містить файл?) then (так)
  :Перегляд вмісту;
  if (Потрібні правки?) then (так)
    :Написати коментар;
    :Натиснути "Повернути" (Return);
    :Статус -> RETURNED;
  else (ні)
    :Виставити оцінку (Grade);
    :Натиснути "Повернути";
    :Статус -> GRADED;
  endif
else (ні)
  :Поставити 0 або написати зауваження;
endif
stop
@enduml